name: "fasta_phage_host_iphop"
description: Predict phage host using iPHoP
keywords:
  - iphop
  - phage
  - host
  - download
  - predict
modules:
  - iphop/download
  - iphop/predict

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end ]`
  - fasta:
      type: file
      description: FASTA file containing phage contigs/scaffolds/chromosomes
      pattern: "*.{fasta,fna,fa}"

output:
  - iphop_genus:
      type: file
      description: File containing integrated host predictions at genus level
      pattern: Host_prediction_to_genus_m*.csv
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@margotl9"
